# Generated by Django 6.1.1 on 2026-09-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='title',
        ),
        migrations.AddField(
            model_name='requirement',
            name='titulo',
            field=models.CharField(default='Sin título', max_length=20),
        ),
    ]
